(defun shrug () (interactive)(insert "¯\\_(ツ)_/¯"))
;;(global-set-key (kbd "C-c C-s") 'shrug)
;; No, this conflicts in org-mode...
;;(global-set-key (kbd "C-c s") 'shrug)
;; No, this conflicts in rg-mode...
